languageCode = "pt-br"
languageName = "Português"
weight = 1
title = "Millennial Idoso"

[params]
  dateFormat = "2 de January de 2006"
  description = ""

  [params.author]
    name = "Millennial Idoso"
    links = [
      { github = "https://github.com/seu-usuario" },
      { bluesky = "https://bsky.app/profile/millenial-idoso.bsky.social" },
    ]
