version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 1,15 * *"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 9 1,15 * *"